# Generated by Django 5.2.11 on 2026-02-22 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contact_document_job'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
