# Generated by Django 5.2.11 on 2026-03-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_job_url_job_interview_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
