# Generated by Django 5.2.11 on 2026-03-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_job_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='offer_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='rejected_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
